apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-autoscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app-autoscale
  template:
    metadata:
      labels:
        app: go-app-autoscale
    spec:
      containers:
        - name: go-app
          image: hrbocutti/go-minikube-docker
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-autoscale-service
spec:
  type: NodePort
  selector:
    app: go-app-autoscale
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30037
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-app-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-app-autoscale
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
