apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-low-capacity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app-low-capacity
  template:
    metadata:
      labels:
        app: go-app-low-capacity
    spec:
      containers:
        - name: go-app
          image: hrbocutti/go-minikube-docker
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-low-capacity-service
spec:
  type: NodePort
  selector:
    app: go-app-low-capacity
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30039
